# [default_session]
# startup_command = "nvim +GoToFile"

[[session]]
name = "tmux config"
path = "~/dot/tmux/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "nvim config"
path = "~/dot/nvim/.config/nvim"
startup_command = "nvim +GoToFile"

[[session]]
name = "wezterm config"
path = "~/dot/wezterm/.config/wezterm"
startup_command = "nvim wezterm.lua"

[[session]]
name = "sesh config"
path = "~/dot/sesh/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "zsh config"
path = "~/dot/zsh"
startup_command = "nvim .zshrc"

[[session]]
name = "dotfiles"
path = "~/dot"
startup_command = "nvim +GoToFile"

