[default_session]
startup_command = "nvim +GoToFile"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "nvim config"
path = "~/.config/nvim"

[[session]]
name = "wezterm config"
path = "~/.config/wezterm"
startup_command = "nvim wezterm.lua"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
