# [default_session]
# startup_command = "nvim +GoToFile"

[[session]]
name = "dotfiles"
path = "~/dot"
startup_command = "nvim ."

[[session]]
name = "Intrum"
path = "~/Projects/stacc/intrum"
startup_command = "nvim ."
